import { type PaperType } from './paperSpecifications.js';
import type { PaperSizeUnit, PaperSpecifications } from './types.js';
export declare function isPaperType(possiblePaperType?: string): possiblePaperType is PaperType;
export declare function getPaperSize(paperType: PaperType, paperSizeUnit?: PaperSizeUnit): PaperSpecifications;
export declare function getPaperSize(paperType: Omit<string, PaperType>, paperSizeUnit?: PaperSizeUnit): undefined;
export declare function getPaperSize(paperType: PaperType, paperSizeUnit?: Omit<string, PaperSizeUnit>): undefined;
export declare function getPaperSize(paperType: Omit<string, PaperType>, paperSizeUnit?: Omit<string, PaperSizeUnit>): undefined;
export declare function getLandscapePaperSize(paperType: PaperType, paperSizeUnit?: PaperSizeUnit): PaperSpecifications;
export declare function getLandscapePaperSize(paperType: Omit<string, PaperType>, paperSizeUnit?: PaperSizeUnit): undefined;
export declare function getLandscapePaperSize(paperType: PaperType, paperSizeUnit?: Omit<string, PaperSizeUnit>): undefined;
export declare function getLandscapePaperSize(paperType: Omit<string, PaperType>, paperSizeUnit?: Omit<string, PaperSizeUnit>): undefined;
export declare function getPaperSizeInInches(paperType: PaperType): PaperSpecifications;
export declare function getPaperSizeInInches(paperType: Omit<string, PaperType>): undefined;
export declare function getPaperSizeInMillimetres(paperType: PaperType): PaperSpecifications;
export declare function getPaperSizeInMillimetres(paperType: Omit<string, PaperType>): undefined;
export { type PaperType, paperSpecifications } from './paperSpecifications.js';
export { type NorthAmericanPaperType, commonNorthAmericanPaperSpecifications, ansiPaperSpecifications, archPaperSpecifications, northAmericanPaperSpecifications, isNorthAmericanPaperType } from './paperSpecifications/northAmerica.js';
export { type IsoPaperType, aSeriesPaperSpecifications, bSeriesPaperSpecifications, cSeriesPaperSpecifications, isoPaperSpecifications, isIsoPaperType } from './paperSpecifications/iso.js';
export type { PaperSpecifications, PaperSizeUnit } from './types.js';
